/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as InstagramRouteImport } from './routes/instagram'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as TiktokRouteImport } from './routes/tiktok'
import { Route as YoutubeRouteImport } from './routes/youtube'
import { Route as ApiBackupRouteImport } from './routes/api/backup'
import { Route as ApiFileRouteImport } from './routes/api/file'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiJobsRouteImport } from './routes/api/jobs'
import { Route as ApiKeepRouteImport } from './routes/api/keep'
import { Route as ApiPartnerRouteImport } from './routes/api/partner'
import { Route as ApiResolveRouteImport } from './routes/api/resolve'
import { Route as ApiStatusRouteImport } from './routes/api/status'
import { Route as ApiTelegramRouteImport } from './routes/api/telegram'
import { Route as DIdRouteImport } from './routes/d.$id'
import { Route as SIdRouteImport } from './routes/s.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const InstagramRoute = InstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const TiktokRoute = TiktokRouteImport.update({
  id: '/tiktok',
  path: '/tiktok',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeRoute = YoutubeRouteImport.update({
  id: '/youtube',
  path: '/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBackupRoute = ApiBackupRouteImport.update({
  id: '/api/backup',
  path: '/api/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFileRoute = ApiFileRouteImport.update({
  id: '/api/file',
  path: '/api/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsRoute = ApiJobsRouteImport.update({
  id: '/api/jobs',
  path: '/api/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeepRoute = ApiKeepRouteImport.update({
  id: '/api/keep',
  path: '/api/keep',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPartnerRoute = ApiPartnerRouteImport.update({
  id: '/api/partner',
  path: '/api/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResolveRoute = ApiResolveRouteImport.update({
  id: '/api/resolve',
  path: '/api/resolve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramRoute = ApiTelegramRouteImport.update({
  id: '/api/telegram',
  path: '/api/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const DIdRoute = DIdRouteImport.update({
  id: '/d/$id',
  path: '/d/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SIdRoute = SIdRouteImport.update({
  id: '/s/$id',
  path: '/s/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/faq': typeof FaqRoute
  '/instagram': typeof InstagramRoute
  '/legal': typeof LegalRoute
  '/tiktok': typeof TiktokRoute
  '/youtube': typeof YoutubeRoute
  '/api/backup': typeof ApiBackupRoute
  '/api/file': typeof ApiFileRoute
  '/api/health': typeof ApiHealthRoute
  '/api/jobs': typeof ApiJobsRoute
  '/api/keep': typeof ApiKeepRoute
  '/api/partner': typeof ApiPartnerRoute
  '/api/resolve': typeof ApiResolveRoute
  '/api/status': typeof ApiStatusRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/d/$id': typeof DIdRoute
  '/s/$id': typeof SIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/faq': typeof FaqRoute
  '/instagram': typeof InstagramRoute
  '/legal': typeof LegalRoute
  '/tiktok': typeof TiktokRoute
  '/youtube': typeof YoutubeRoute
  '/api/backup': typeof ApiBackupRoute
  '/api/file': typeof ApiFileRoute
  '/api/health': typeof ApiHealthRoute
  '/api/jobs': typeof ApiJobsRoute
  '/api/keep': typeof ApiKeepRoute
  '/api/partner': typeof ApiPartnerRoute
  '/api/resolve': typeof ApiResolveRoute
  '/api/status': typeof ApiStatusRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/d/$id': typeof DIdRoute
  '/s/$id': typeof SIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/faq': typeof FaqRoute
  '/instagram': typeof InstagramRoute
  '/legal': typeof LegalRoute
  '/tiktok': typeof TiktokRoute
  '/youtube': typeof YoutubeRoute
  '/api/backup': typeof ApiBackupRoute
  '/api/file': typeof ApiFileRoute
  '/api/health': typeof ApiHealthRoute
  '/api/jobs': typeof ApiJobsRoute
  '/api/keep': typeof ApiKeepRoute
  '/api/partner': typeof ApiPartnerRoute
  '/api/resolve': typeof ApiResolveRoute
  '/api/status': typeof ApiStatusRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/d/$id': typeof DIdRoute
  '/s/$id': typeof SIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/faq'
    | '/instagram'
    | '/legal'
    | '/tiktok'
    | '/youtube'
    | '/api/backup'
    | '/api/file'
    | '/api/health'
    | '/api/jobs'
    | '/api/keep'
    | '/api/partner'
    | '/api/resolve'
    | '/api/status'
    | '/api/telegram'
    | '/d/$id'
    | '/s/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/faq'
    | '/instagram'
    | '/legal'
    | '/tiktok'
    | '/youtube'
    | '/api/backup'
    | '/api/file'
    | '/api/health'
    | '/api/jobs'
    | '/api/keep'
    | '/api/partner'
    | '/api/resolve'
    | '/api/status'
    | '/api/telegram'
    | '/d/$id'
    | '/s/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/faq'
    | '/instagram'
    | '/legal'
    | '/tiktok'
    | '/youtube'
    | '/api/backup'
    | '/api/file'
    | '/api/health'
    | '/api/jobs'
    | '/api/keep'
    | '/api/partner'
    | '/api/resolve'
    | '/api/status'
    | '/api/telegram'
    | '/d/$id'
    | '/s/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  FaqRoute: typeof FaqRoute
  InstagramRoute: typeof InstagramRoute
  LegalRoute: typeof LegalRoute
  TiktokRoute: typeof TiktokRoute
  YoutubeRoute: typeof YoutubeRoute
  ApiBackupRoute: typeof ApiBackupRoute
  ApiFileRoute: typeof ApiFileRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiJobsRoute: typeof ApiJobsRoute
  ApiKeepRoute: typeof ApiKeepRoute
  ApiPartnerRoute: typeof ApiPartnerRoute
  ApiResolveRoute: typeof ApiResolveRoute
  ApiStatusRoute: typeof ApiStatusRoute
  ApiTelegramRoute: typeof ApiTelegramRoute
  DIdRoute: typeof DIdRoute
  SIdRoute: typeof SIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram': {
      id: '/instagram'
      path: '/instagram'
      fullPath: '/instagram'
      preLoaderRoute: typeof InstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiktok': {
      id: '/tiktok'
      path: '/tiktok'
      fullPath: '/tiktok'
      preLoaderRoute: typeof TiktokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube': {
      id: '/youtube'
      path: '/youtube'
      fullPath: '/youtube'
      preLoaderRoute: typeof YoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/backup': {
      id: '/api/backup'
      path: '/api/backup'
      fullPath: '/api/backup'
      preLoaderRoute: typeof ApiBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file': {
      id: '/api/file'
      path: '/api/file'
      fullPath: '/api/file'
      preLoaderRoute: typeof ApiFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs': {
      id: '/api/jobs'
      path: '/api/jobs'
      fullPath: '/api/jobs'
      preLoaderRoute: typeof ApiJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keep': {
      id: '/api/keep'
      path: '/api/keep'
      fullPath: '/api/keep'
      preLoaderRoute: typeof ApiKeepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/partner': {
      id: '/api/partner'
      path: '/api/partner'
      fullPath: '/api/partner'
      preLoaderRoute: typeof ApiPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resolve': {
      id: '/api/resolve'
      path: '/api/resolve'
      fullPath: '/api/resolve'
      preLoaderRoute: typeof ApiResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram': {
      id: '/api/telegram'
      path: '/api/telegram'
      fullPath: '/api/telegram'
      preLoaderRoute: typeof ApiTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$id': {
      id: '/d/$id'
      path: '/d/$id'
      fullPath: '/d/$id'
      preLoaderRoute: typeof DIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$id': {
      id: '/s/$id'
      path: '/s/$id'
      fullPath: '/s/$id'
      preLoaderRoute: typeof SIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  FaqRoute: FaqRoute,
  InstagramRoute: InstagramRoute,
  LegalRoute: LegalRoute,
  TiktokRoute: TiktokRoute,
  YoutubeRoute: YoutubeRoute,
  ApiBackupRoute: ApiBackupRoute,
  ApiFileRoute: ApiFileRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiJobsRoute: ApiJobsRoute,
  ApiKeepRoute: ApiKeepRoute,
  ApiPartnerRoute: ApiPartnerRoute,
  ApiResolveRoute: ApiResolveRoute,
  ApiStatusRoute: ApiStatusRoute,
  ApiTelegramRoute: ApiTelegramRoute,
  DIdRoute: DIdRoute,
  SIdRoute: SIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
