/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as FacebookRouteImport } from './routes/facebook'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as InstagramRouteImport } from './routes/instagram'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SnapchatRouteImport } from './routes/snapchat'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TiktokRouteImport } from './routes/tiktok'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as XRouteImport } from './routes/x'
import { Route as YoutubeRouteImport } from './routes/youtube'
import { Route as ApiBackupRouteImport } from './routes/api/backup'
import { Route as ApiFileRouteImport } from './routes/api/file'
import { Route as ApiGrabRouteImport } from './routes/api/grab'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiJobsRouteImport } from './routes/api/jobs'
import { Route as ApiKeepRouteImport } from './routes/api/keep'
import { Route as ApiPartnerRouteImport } from './routes/api/partner'
import { Route as ApiRemindRouteImport } from './routes/api/remind'
import { Route as ApiResolveRouteImport } from './routes/api/resolve'
import { Route as ApiStatusRouteImport } from './routes/api/status'
import { Route as ApiTelegramRouteImport } from './routes/api/telegram'
import { Route as DIdRouteImport } from './routes/d.$id'
import { Route as DlIdRouteImport } from './routes/dl.$id'
import { Route as SIdRouteImport } from './routes/s.$id'
import { Route as ApiPaypalWebhookRouteImport } from './routes/api/paypal/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FacebookRoute = FacebookRouteImport.update({
  id: '/facebook',
  path: '/facebook',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const InstagramRoute = InstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SnapchatRoute = SnapchatRouteImport.update({
  id: '/snapchat',
  path: '/snapchat',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TiktokRoute = TiktokRouteImport.update({
  id: '/tiktok',
  path: '/tiktok',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const XRoute = XRouteImport.update({
  id: '/x',
  path: '/x',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeRoute = YoutubeRouteImport.update({
  id: '/youtube',
  path: '/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBackupRoute = ApiBackupRouteImport.update({
  id: '/api/backup',
  path: '/api/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFileRoute = ApiFileRouteImport.update({
  id: '/api/file',
  path: '/api/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGrabRoute = ApiGrabRouteImport.update({
  id: '/api/grab',
  path: '/api/grab',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsRoute = ApiJobsRouteImport.update({
  id: '/api/jobs',
  path: '/api/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeepRoute = ApiKeepRouteImport.update({
  id: '/api/keep',
  path: '/api/keep',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPartnerRoute = ApiPartnerRouteImport.update({
  id: '/api/partner',
  path: '/api/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemindRoute = ApiRemindRouteImport.update({
  id: '/api/remind',
  path: '/api/remind',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResolveRoute = ApiResolveRouteImport.update({
  id: '/api/resolve',
  path: '/api/resolve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramRoute = ApiTelegramRouteImport.update({
  id: '/api/telegram',
  path: '/api/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const DIdRoute = DIdRouteImport.update({
  id: '/d/$id',
  path: '/d/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DlIdRoute = DlIdRouteImport.update({
  id: '/dl/$id',
  path: '/dl/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SIdRoute = SIdRouteImport.update({
  id: '/s/$id',
  path: '/s/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaypalWebhookRoute = ApiPaypalWebhookRouteImport.update({
  id: '/api/paypal/webhook',
  path: '/api/paypal/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/facebook': typeof FacebookRoute
  '/faq': typeof FaqRoute
  '/instagram': typeof InstagramRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/snapchat': typeof SnapchatRoute
  '/terms': typeof TermsRoute
  '/tiktok': typeof TiktokRoute
  '/workspace': typeof WorkspaceRoute
  '/x': typeof XRoute
  '/youtube': typeof YoutubeRoute
  '/api/backup': typeof ApiBackupRoute
  '/api/file': typeof ApiFileRoute
  '/api/grab': typeof ApiGrabRoute
  '/api/health': typeof ApiHealthRoute
  '/api/jobs': typeof ApiJobsRoute
  '/api/keep': typeof ApiKeepRoute
  '/api/partner': typeof ApiPartnerRoute
  '/api/remind': typeof ApiRemindRoute
  '/api/resolve': typeof ApiResolveRoute
  '/api/status': typeof ApiStatusRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/d/$id': typeof DIdRoute
  '/dl/$id': typeof DlIdRoute
  '/s/$id': typeof SIdRoute
  '/api/paypal/webhook': typeof ApiPaypalWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/facebook': typeof FacebookRoute
  '/faq': typeof FaqRoute
  '/instagram': typeof InstagramRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/snapchat': typeof SnapchatRoute
  '/terms': typeof TermsRoute
  '/tiktok': typeof TiktokRoute
  '/workspace': typeof WorkspaceRoute
  '/x': typeof XRoute
  '/youtube': typeof YoutubeRoute
  '/api/backup': typeof ApiBackupRoute
  '/api/file': typeof ApiFileRoute
  '/api/grab': typeof ApiGrabRoute
  '/api/health': typeof ApiHealthRoute
  '/api/jobs': typeof ApiJobsRoute
  '/api/keep': typeof ApiKeepRoute
  '/api/partner': typeof ApiPartnerRoute
  '/api/remind': typeof ApiRemindRoute
  '/api/resolve': typeof ApiResolveRoute
  '/api/status': typeof ApiStatusRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/d/$id': typeof DIdRoute
  '/dl/$id': typeof DlIdRoute
  '/s/$id': typeof SIdRoute
  '/api/paypal/webhook': typeof ApiPaypalWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/facebook': typeof FacebookRoute
  '/faq': typeof FaqRoute
  '/instagram': typeof InstagramRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/snapchat': typeof SnapchatRoute
  '/terms': typeof TermsRoute
  '/tiktok': typeof TiktokRoute
  '/workspace': typeof WorkspaceRoute
  '/x': typeof XRoute
  '/youtube': typeof YoutubeRoute
  '/api/backup': typeof ApiBackupRoute
  '/api/file': typeof ApiFileRoute
  '/api/grab': typeof ApiGrabRoute
  '/api/health': typeof ApiHealthRoute
  '/api/jobs': typeof ApiJobsRoute
  '/api/keep': typeof ApiKeepRoute
  '/api/partner': typeof ApiPartnerRoute
  '/api/remind': typeof ApiRemindRoute
  '/api/resolve': typeof ApiResolveRoute
  '/api/status': typeof ApiStatusRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/d/$id': typeof DIdRoute
  '/dl/$id': typeof DlIdRoute
  '/s/$id': typeof SIdRoute
  '/api/paypal/webhook': typeof ApiPaypalWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/facebook'
    | '/faq'
    | '/instagram'
    | '/legal'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/snapchat'
    | '/terms'
    | '/tiktok'
    | '/workspace'
    | '/x'
    | '/youtube'
    | '/api/backup'
    | '/api/file'
    | '/api/grab'
    | '/api/health'
    | '/api/jobs'
    | '/api/keep'
    | '/api/partner'
    | '/api/remind'
    | '/api/resolve'
    | '/api/status'
    | '/api/telegram'
    | '/d/$id'
    | '/dl/$id'
    | '/s/$id'
    | '/api/paypal/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/facebook'
    | '/faq'
    | '/instagram'
    | '/legal'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/snapchat'
    | '/terms'
    | '/tiktok'
    | '/workspace'
    | '/x'
    | '/youtube'
    | '/api/backup'
    | '/api/file'
    | '/api/grab'
    | '/api/health'
    | '/api/jobs'
    | '/api/keep'
    | '/api/partner'
    | '/api/remind'
    | '/api/resolve'
    | '/api/status'
    | '/api/telegram'
    | '/d/$id'
    | '/dl/$id'
    | '/s/$id'
    | '/api/paypal/webhook'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/facebook'
    | '/faq'
    | '/instagram'
    | '/legal'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/snapchat'
    | '/terms'
    | '/tiktok'
    | '/workspace'
    | '/x'
    | '/youtube'
    | '/api/backup'
    | '/api/file'
    | '/api/grab'
    | '/api/health'
    | '/api/jobs'
    | '/api/keep'
    | '/api/partner'
    | '/api/remind'
    | '/api/resolve'
    | '/api/status'
    | '/api/telegram'
    | '/d/$id'
    | '/dl/$id'
    | '/s/$id'
    | '/api/paypal/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  FacebookRoute: typeof FacebookRoute
  FaqRoute: typeof FaqRoute
  InstagramRoute: typeof InstagramRoute
  LegalRoute: typeof LegalRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SnapchatRoute: typeof SnapchatRoute
  TermsRoute: typeof TermsRoute
  TiktokRoute: typeof TiktokRoute
  WorkspaceRoute: typeof WorkspaceRoute
  XRoute: typeof XRoute
  YoutubeRoute: typeof YoutubeRoute
  ApiBackupRoute: typeof ApiBackupRoute
  ApiFileRoute: typeof ApiFileRoute
  ApiGrabRoute: typeof ApiGrabRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiJobsRoute: typeof ApiJobsRoute
  ApiKeepRoute: typeof ApiKeepRoute
  ApiPartnerRoute: typeof ApiPartnerRoute
  ApiRemindRoute: typeof ApiRemindRoute
  ApiResolveRoute: typeof ApiResolveRoute
  ApiStatusRoute: typeof ApiStatusRoute
  ApiTelegramRoute: typeof ApiTelegramRoute
  DIdRoute: typeof DIdRoute
  DlIdRoute: typeof DlIdRoute
  SIdRoute: typeof SIdRoute
  ApiPaypalWebhookRoute: typeof ApiPaypalWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facebook': {
      id: '/facebook'
      path: '/facebook'
      fullPath: '/facebook'
      preLoaderRoute: typeof FacebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram': {
      id: '/instagram'
      path: '/instagram'
      fullPath: '/instagram'
      preLoaderRoute: typeof InstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snapchat': {
      id: '/snapchat'
      path: '/snapchat'
      fullPath: '/snapchat'
      preLoaderRoute: typeof SnapchatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiktok': {
      id: '/tiktok'
      path: '/tiktok'
      fullPath: '/tiktok'
      preLoaderRoute: typeof TiktokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/x': {
      id: '/x'
      path: '/x'
      fullPath: '/x'
      preLoaderRoute: typeof XRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube': {
      id: '/youtube'
      path: '/youtube'
      fullPath: '/youtube'
      preLoaderRoute: typeof YoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/backup': {
      id: '/api/backup'
      path: '/api/backup'
      fullPath: '/api/backup'
      preLoaderRoute: typeof ApiBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file': {
      id: '/api/file'
      path: '/api/file'
      fullPath: '/api/file'
      preLoaderRoute: typeof ApiFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/grab': {
      id: '/api/grab'
      path: '/api/grab'
      fullPath: '/api/grab'
      preLoaderRoute: typeof ApiGrabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs': {
      id: '/api/jobs'
      path: '/api/jobs'
      fullPath: '/api/jobs'
      preLoaderRoute: typeof ApiJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keep': {
      id: '/api/keep'
      path: '/api/keep'
      fullPath: '/api/keep'
      preLoaderRoute: typeof ApiKeepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/partner': {
      id: '/api/partner'
      path: '/api/partner'
      fullPath: '/api/partner'
      preLoaderRoute: typeof ApiPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remind': {
      id: '/api/remind'
      path: '/api/remind'
      fullPath: '/api/remind'
      preLoaderRoute: typeof ApiRemindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resolve': {
      id: '/api/resolve'
      path: '/api/resolve'
      fullPath: '/api/resolve'
      preLoaderRoute: typeof ApiResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram': {
      id: '/api/telegram'
      path: '/api/telegram'
      fullPath: '/api/telegram'
      preLoaderRoute: typeof ApiTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$id': {
      id: '/d/$id'
      path: '/d/$id'
      fullPath: '/d/$id'
      preLoaderRoute: typeof DIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dl/$id': {
      id: '/dl/$id'
      path: '/dl/$id'
      fullPath: '/dl/$id'
      preLoaderRoute: typeof DlIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$id': {
      id: '/s/$id'
      path: '/s/$id'
      fullPath: '/s/$id'
      preLoaderRoute: typeof SIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paypal/webhook': {
      id: '/api/paypal/webhook'
      path: '/api/paypal/webhook'
      fullPath: '/api/paypal/webhook'
      preLoaderRoute: typeof ApiPaypalWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  FacebookRoute: FacebookRoute,
  FaqRoute: FaqRoute,
  InstagramRoute: InstagramRoute,
  LegalRoute: LegalRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SnapchatRoute: SnapchatRoute,
  TermsRoute: TermsRoute,
  TiktokRoute: TiktokRoute,
  WorkspaceRoute: WorkspaceRoute,
  XRoute: XRoute,
  YoutubeRoute: YoutubeRoute,
  ApiBackupRoute: ApiBackupRoute,
  ApiFileRoute: ApiFileRoute,
  ApiGrabRoute: ApiGrabRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiJobsRoute: ApiJobsRoute,
  ApiKeepRoute: ApiKeepRoute,
  ApiPartnerRoute: ApiPartnerRoute,
  ApiRemindRoute: ApiRemindRoute,
  ApiResolveRoute: ApiResolveRoute,
  ApiStatusRoute: ApiStatusRoute,
  ApiTelegramRoute: ApiTelegramRoute,
  DIdRoute: DIdRoute,
  DlIdRoute: DlIdRoute,
  SIdRoute: SIdRoute,
  ApiPaypalWebhookRoute: ApiPaypalWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
